# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Thu Sep 22 18:51:20 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 903)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logingTaskLay = QtGui.QVBoxLayout()
        self.logingTaskLay.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.logingTaskLay.setObjectName("logingTaskLay")
        self.logingLay = QtGui.QHBoxLayout()
        self.logingLay.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.logingLay.setObjectName("logingLay")
        self.loginButton = QtGui.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.logingLay.addWidget(self.loginButton)
        self.updateButton = QtGui.QPushButton(self.centralwidget)
        self.updateButton.setObjectName("updateButton")
        self.logingLay.addWidget(self.updateButton)
        self.logingTaskLay.addLayout(self.logingLay)
        self.taskLay = QtGui.QVBoxLayout()
        self.taskLay.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.taskLay.setObjectName("taskLay")
        self.taskLabel = QtGui.QLabel(self.centralwidget)
        self.taskLabel.setEnabled(True)
        self.taskLabel.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.taskLabel.setFont(font)
        self.taskLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.taskLabel.setObjectName("taskLabel")
        self.taskLay.addWidget(self.taskLabel)
        self.taskTable = QtGui.QTableWidget(self.centralwidget)
        self.taskTable.setObjectName("taskTable")
        self.taskTable.setColumnCount(9)
        self.taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(8, item)
        self.taskLay.addWidget(self.taskTable)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inprogressButton = QtGui.QPushButton(self.centralwidget)
        self.inprogressButton.setObjectName("inprogressButton")
        self.horizontalLayout_3.addWidget(self.inprogressButton)
        self.apprubalButton = QtGui.QPushButton(self.centralwidget)
        self.apprubalButton.setObjectName("apprubalButton")
        self.horizontalLayout_3.addWidget(self.apprubalButton)
        self.taskLay.addLayout(self.horizontalLayout_3)
        self.logingTaskLay.addLayout(self.taskLay)
        self.logingTaskLay.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.logingTaskLay)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.loginButton.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.taskLabel.setText(QtGui.QApplication.translate("MainWindow", "Current Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Task Name", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "DaysLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "EndDate", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Complexity", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.inprogressButton.setText(QtGui.QApplication.translate("MainWindow", "Set In Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.apprubalButton.setText(QtGui.QApplication.translate("MainWindow", "Submit for Approval", None, QtGui.QApplication.UnicodeUTF8))

