# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supWindow.ui'
#
# Created: Thu Nov 24 17:21:34 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 1210)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logingTaskLay = QtGui.QVBoxLayout()
        self.logingTaskLay.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.logingTaskLay.setObjectName("logingTaskLay")
        self.logingLay = QtGui.QHBoxLayout()
        self.logingLay.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.logingLay.setObjectName("logingLay")
        self.loginButton = QtGui.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.logingLay.addWidget(self.loginButton)
        self.updateButton = QtGui.QPushButton(self.centralwidget)
        self.updateButton.setObjectName("updateButton")
        self.logingLay.addWidget(self.updateButton)
        self.logingTaskLay.addLayout(self.logingLay)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.taskLabel = QtGui.QLabel(self.centralwidget)
        self.taskLabel.setEnabled(True)
        self.taskLabel.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.taskLabel.setFont(font)
        self.taskLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.taskLabel.setObjectName("taskLabel")
        self.horizontalLayout.addWidget(self.taskLabel)
        self.hideRdy_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.hideRdy_checkBox.setObjectName("hideRdy_checkBox")
        self.horizontalLayout.addWidget(self.hideRdy_checkBox)
        self.hideIp_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.hideIp_checkBox.setObjectName("hideIp_checkBox")
        self.horizontalLayout.addWidget(self.hideIp_checkBox)
        self.hideCmpt_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.hideCmpt_checkBox.setObjectName("hideCmpt_checkBox")
        self.horizontalLayout.addWidget(self.hideCmpt_checkBox)
        self.hideApr_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.hideApr_checkBox.setObjectName("hideApr_checkBox")
        self.horizontalLayout.addWidget(self.hideApr_checkBox)
        self.hideDeliver_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.hideDeliver_checkBox.setObjectName("hideDeliver_checkBox")
        self.horizontalLayout.addWidget(self.hideDeliver_checkBox)
        self.logingTaskLay.addLayout(self.horizontalLayout)
        self.taskLay = QtGui.QVBoxLayout()
        self.taskLay.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.taskLay.setObjectName("taskLay")
        self.taskTable = QtGui.QTableWidget(self.centralwidget)
        self.taskTable.setObjectName("taskTable")
        self.taskTable.setColumnCount(10)
        self.taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(9, item)
        self.taskLay.addWidget(self.taskTable)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.downloadSubmitionsButton = QtGui.QPushButton(self.centralwidget)
        self.downloadSubmitionsButton.setObjectName("downloadSubmitionsButton")
        self.horizontalLayout_3.addWidget(self.downloadSubmitionsButton)
        self.statusButton = QtGui.QPushButton(self.centralwidget)
        self.statusButton.setObjectName("statusButton")
        self.horizontalLayout_3.addWidget(self.statusButton)
        self.taskDelivery_pushButton = QtGui.QPushButton(self.centralwidget)
        self.taskDelivery_pushButton.setObjectName("taskDelivery_pushButton")
        self.horizontalLayout_3.addWidget(self.taskDelivery_pushButton)
        self.getDelivery = QtGui.QPushButton(self.centralwidget)
        self.getDelivery.setMaximumSize(QtCore.QSize(150, 16777215))
        self.getDelivery.setObjectName("getDelivery")
        self.horizontalLayout_3.addWidget(self.getDelivery)
        self.taskLay.addLayout(self.horizontalLayout_3)
        self.logingTaskLay.addLayout(self.taskLay)
        self.horizontalLayout_2.addLayout(self.logingTaskLay)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.loginButton.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.taskLabel.setText(QtGui.QApplication.translate("MainWindow", "Current Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.hideRdy_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Hide Rdy", None, QtGui.QApplication.UnicodeUTF8))
        self.hideIp_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Hide in Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.hideCmpt_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Hide Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.hideApr_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Hide Approved", None, QtGui.QApplication.UnicodeUTF8))
        self.hideDeliver_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Hide Delivery", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Task Name", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "DaysLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "EndDate", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Complexity", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadSubmitionsButton.setText(QtGui.QApplication.translate("MainWindow", "downloadSubmitions", None, QtGui.QApplication.UnicodeUTF8))
        self.statusButton.setText(QtGui.QApplication.translate("MainWindow", "Update Status", None, QtGui.QApplication.UnicodeUTF8))
        self.taskDelivery_pushButton.setText(QtGui.QApplication.translate("MainWindow", "task Delivery", None, QtGui.QApplication.UnicodeUTF8))
        self.getDelivery.setText(QtGui.QApplication.translate("MainWindow", "get Delivery", None, QtGui.QApplication.UnicodeUTF8))

